---

#docker_project_repository: https://github.com/JosephLutz/docker-project.git

# the base directory where the docker projects will be checked out
docker_projects_dir: '/opt/docker/{{ docker_image_tag }}'
docker_restore_config_base_dir: '/etc/docker_container.conf/{{ docker_image_tag }}'

# restore directories to temporarly store data being restored into docker containers
docker_backup_dir: '/tmp/docker'
docker_restore_dir: '{{ bacula_dest }}{{ docker_backup_dir }}'
