---

# The hostname passed as an envirnment variable into the container
container_addr_map:
  git:
    ip_addr: '127.0.0.1'
    hostname: git.example.com

# the port mappings used when starting the container
container_port_map:
  git:
    port_args: '-P'

# database usernames and passwords
gitlab_db_user: novatech

# must pass in the following variables
# gitlab_db_password: ''
