---
- name: Copy script
  copy:
    src: fetch_merge_requests.rb
    dest: '{{gitlab_docker_backup_dir}}'
    owner: root
    group: root
    mode: 'u=rwx,g=rwx,o=rwx'

- name: Run script
  command: >
    docker exec '{{gitlab_container_name}}'
    gitlab-rails runner /mnt/backups/fetch_merge_requests.rb
