---
dependencies:

- name: docker-common as a dependency
  role: docker-common

- name: docker-openssl as a dependency
  role: docker-openssl
  tags:
  - openssl_container

- name: docker-openldap as a dependency
  role: docker-openldap
  tags:
  - openldap_container
