- name: Create temp directory for policy creation
  command: mktemp -d /tmp/ansible-bacula-storage.XXXXXXXX
  register: bacula_storage_tmp_dir
- name: Copy baculatape type enforcement file
  copy:
    src: baculatape.te
    dest: '{{ bacula_storage_tmp_dir.stdout }}/baculatape.te'
    owner: root
    group: root
    mode: 0640
- name: Run checkmodule on baculatape.te
  command: /usr/bin/checkmodule -M -m -o baculatape.mod baculatape.te
  args:
    chdir: "{{ bacula_storage_tmp_dir.stdout }}"
- name: Build baculatape module
  command: /usr/bin/semodule_package -o baculatape.pp -m baculatape.mod
  args:
    chdir: "{{ bacula_storage_tmp_dir.stdout }}"
- name: Install baculatape module
  command: /usr/sbin/semodule -i baculatape.pp
  args:
    chdir: "{{ bacula_storage_tmp_dir.stdout }}"
- name: Delete temp directory
  file:
    path: '{{ bacula_storage_tmp_dir.stdout }} '
    state: absent
