---
# vars file for buildbot

# the name of the image being duilt and used for the container
buildbot_image_repo: https://github.com/novatechweb/docker-buildbot.git
buildbot_image_name: '{{ docker_registry_username }}/buildbot'

# the name of the container being started
buildbot_container_name: '{{ docker_name_prefix }}buildbot'

# the name of the data-volume used by the container
buildbot_dv_name: '{{ docker_name_prefix }}buildbot_DV'

# restore directories to temporarly store data being restored into docker containers
buildbot_docker_backup_dir: '{{ docker_backup_dir }}/buildbot'
host_buildbot_docker_restore_dir: '{{ bacula_dest }}{{ buildbot_docker_backup_dir }}'
