---
dependencies:

- name: docker-common as a dependency
  role: docker-common

- name: docker-pull-images as a dependency
  role: docker-pull-images

- name: docker-openssl as a dependency
  role: docker-openssl
  tags:
  - openssl_container
