---
# file: roles/docker-openldap/tasks/restore.yaml

# *****************************************************************************
# Get data from tape

- name: find files
  files_in_dir:
    path: '{{ host_openldap_docker_restore_dir }}'
  register: ldap_backup

- name: Get data-volume data from tape
  bacula:
    command: restore
    storage: '{{ bacula_storage }}'
    fileset: '{{ bacula_fileset }}'
    dest: '{{ bacula_dest }}'
    path_to_restore: '{{ openldap_docker_backup_dir }}'
  when: ldap_backup.file_list == []

- name: Set permissions for data-volume data
  file:
    path: '{{ host_openldap_docker_restore_dir }}/{{ item.ldif_file }}'
    state: touch
    owner: root
    group: root
    mode: 'u=rw,g=rw,o='
  with_items: '{{ openldap_backup_files }}'

# *****************************************************************************
# restore the openldap backup

- name: stop container (ldap)
  docker_container:
    name: '{{ openldap_container_name }}'
    state: stopped

- name: restore ldif files
  docker_container:
    name: '{{ openldap_container_name }}-restore-{{ item.dbnum }}'
    detach: false
    restart_policy: no
    volumes:
      - '{{ openssl_dv_name }}:/etc/ssl/private:z'
      - '{{ openldap_cv_name }}:/etc/ldap:z'
      - '{{ openldap_dv_name }}:/var/lib/ldap:z'
      - '{{ openldap_docker_restore_dir }}/{{ item.ldif_file }}:/tmp/import_export/{{ item.ldif_file }}:z'
    image: '{{ openldap_image_name }}:{{ docker_image_tag }}'
    command: ['apply_ldif', '-n', '{{ item.dbnum }}', '-l', '{{ item.ldif_file }}']
  with_items: '{{ openldap_backup_files }}'

- name: remove ldif file restoration container
  docker_container:
    name: '{{ openldap_container_name }}-restore-{{ item.dbnum }}'
    state: absent
  with_items: '{{ openldap_backup_files }}'

# *****************************************************************************
# cleanup

- name: Remove database backup file
  file:
    path: '{{ host_openldap_docker_restore_dir }}'
    state: absent

- name: State file
  shell: 'date --rfc-3339=seconds > {{ docker_restore_config_base_dir }}/{{ openldap_dv_name }}/restore.date.txt'
  when: st_openldap_restore.stat.exists == False
