---
# passwords
mariadb_root_password:               '{{ lookup("password", playbook_dir + "/credentials/mariadb/root"   , length=20) }}'
bacula_director_password:            '{{ lookup("password", playbook_dir + "/credentials/bacula/director", length=20) }}'
bacula_monitor_password:             '{{ lookup("password", playbook_dir + "/credentials/bacula/monitor" , length=20) }}'
mariadb_bacula_password:             '{{ lookup("password", playbook_dir + "/credentials/bacula/mariadb" , length=20) }}'
