---

- name: Setup | create user
  user:
    name: ansibleremote
    comment: "Ansible Remote"
    generate_ssh_key: yes
    createhome: yes
    system: yes

- name: Setup | authorized key upload
  authorized_key:
    user: ansibleremote
    key: '{{ lookup("file", item) }}'
    path: '/home/ansibleremote/.ssh/authorized_keys'
    manage_dir: no
  with_fileglob:
  - ../../../public_keys/*.pub

- name: Sudoers | touch sudoers.d file
  file:
    path: /etc/sudoers.d/00_ansibleremote
    owner: root
    group: root
    mode: 'u=r,g=r,o='
    state: touch

- name: Sudoers | update sudoers file and validate
  lineinfile:
    dest: /etc/sudoers.d/00_ansibleremote
    insertafter: EOF
    line: 'ansibleremote ALL=(ALL) NOPASSWD: ALL'
    regexp: 'ansibleremote ALL=(ALL) NOPASSWD: ALL'
    state: present

- name: lockdown root user
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^[#]?PermitRootLogin .*$'
    line: 'PermitRootLogin no'
    state: present

- name: restart sshd service
  service:
    name: sshd
    state: restarted
