---
dependency:
  name: galaxy

driver:
  name: docker
  safe_files:
    - nexus-downloads

lint:
  name: yamllint

platforms:
  - name: ubuntu-16.04
    image: thoteam/ansible-ubuntu16_04-apache-java
    image_version: latest
    command: /lib/systemd/systemd
    privileged: true
    ports:
      - 8090:443
  - name: centos-7
    image: thoteam/ansible-centos7-apache-java
    image_version: latest
    command: /usr/sbin/init
    privileged: true
    ports:
      - 8091:443

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: default
  check_sequence:
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - prepare
    - converge
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - check
    - verify
    - destroy

verifier:
  name: testinfra
  lint:
    name: flake8
