---

# The hostname passed as an envirnment variable into the container
container_addr_map:
  ldap:
    ip_addr: '127.0.0.1'
    hostname: ldap.example.com
  phpldapadmin:
    ip_addr: '127.0.0.1'
    hostname: ldap.example.com

# the port mappings used when starting the container
container_port_map:
  ldap:
    port_args:
      - '{{ container_addr_map.ldap.ip_addr }}:389:389'
      - '{{ container_addr_map.ldap.ip_addr }}:636:636'
  phpldapadmin:
    port_args: 
      - '{{ container_addr_map.phpldapadmin.ip_addr }}:80:80'
      - '{{ container_addr_map.phpldapadmin.ip_addr }}:443:443'

openldap_backup_files:
  - ldif_file: LDAP_database_0000.ldif
    dbnum: 0
  - ldif_file: LDAP_database_0001.ldif
    dbnum: 1

# Network names
docker_network_frontend: 'frontend'
