---

# The hostname passed as an envirnment variable into the container
container_addr_map:
  mantisbt:
    ip_addr: '127.0.0.1'
    hostname: mantis.example.com

# the port mappings used when starting the container
container_port_map:
  mantisbt:
    port_args: '-p {{ container_addr_map.mantisbt.ip_addr }}:80:80 -p {{ container_addr_map.mantisbt.ip_addr }}:443:443'

# database usernames and passwords
mantisbt_db_user: novatech

# must pass in the following variables
# mantisbt_db_root_password: ''
# mantisbt_db_password: ''

# Network names
docker_network_frontend: 'frontend'
