---
# tasks file for bacula-restores

- name: List bacula storage
  find:
    paths: "{{bacula_storage}}"
    file_type: file
    recurse: yes
  register: bacula_restores_list

- name: Create bacula storage symlinks
  file:
    path: '{{ item.path | replace("{{bacula_storage}}","{{bacula_dest}}") | dirname }}'
    state: directory
    force: yes
    mode: 0777
  with_items: '{{ bacula_restores_list.files }}'

- name: Create bacula storage directories
  file:
    src: '{{ item.path }}'
    dest: '{{ item.path | replace("{{bacula_storage}}","{{bacula_dest}}") }}'
    state: link
    force: yes
    mode: '{{ item.mode }}'
  with_items: '{{ bacula_restores_list.files }}'
