---
# tasks file for bacula-restores

- name: Synchronize bacula storage to restore directory
  synchronize:
    dest: "{{bacula_dest}}/" # required. Path on the destination host that will be synchronized from the source; The path can be absolute or relative.
    src: "{{bacula_storage_path}}/" # required. Path on the source host that will be synchronized to the destination; The path can be absolute or relative.
    delete: yes # not required. Delete files in C(dest) that don't exist (after transfer, not before) in the C(src) path. This option requires C(recursive=yes).
    archive: yes # not required. Mirrors the rsync archive flag, enables recursive, links, perms, times, owner, group flags and -D.
    link_dest: "{{bacula_storage_path}}/" # not required. add a destination to hard link against during the rsync.
  delegate_to: "{{ inventory_hostname }}"
