---
# tasks file for bacula-restores

# - name: List bacula storage
#   find:
#     paths: "{{bacula_storage}}"
#     file_type: file
#     recurse: yes
#   register: bacula_storage_list

# - name: Prepare backup file
#   include_tasks: prepare_backup_file.yml
#   loop: '{{bacula_storage_list.files}}'

- name: synchronize backup storage
  synchronize:
    src: "{{bacula_storage}}/"
    dest: "{{bacula_dest}}/"
    link_dest: "{{bacula_storage}}/"
    archive: yes
    delete: yes
  delegate_to: "{{ inventory_hostname }}"
