---
# file: roles/docker-svn/tasks/restore.yaml

# *****************************************************************************
# Get data from tape

- name: find files
  files_in_dir:
    path: '{{ host_svn_docker_restore_dir }}'
  register: svn_repo_backup

- name: data from tape
  bacula:
    command: restore
    storage: '{{ bacula_storage }}'
    fileset: '{{ bacula_fileset }}'
    dest: '{{ bacula_dest }}'
    path_to_restore: '{{ svn_docker_backup_dir }}'
  when: svn_repo_backup.file_list == []

- name: find files
  files_in_dir:
    path: '{{ host_svn_docker_restore_dir }}'
  register: svn_repo_backup

# - name: File permissions
#   file:
#     path: '{{ host_svn_docker_restore_dir }}/{{ item }}'
#     state: touch
#     owner: root
#     group: root
#     mode: 'u=rwx,g=rwx,o='
#   with_items: '{{ svn_repo_backup.file_list | default([]) }}'

# *****************************************************************************
# restore the svn backup

- name: restore svn repositories
  docker_container:
    detach: False
    volumes:
      - '{{ svn_dv_name }}:/var/lib/svn:z'
      - '{{ host_svn_docker_restore_dir }}:/tmp/import_export:z'
    image: '{{ svn_image_name }}:{{ docker_image_tag }}'
    command: ['import', '{{ svn_repos }}']
    name: 'svn_restore'
  when: not((svn_repos is undefined) or (svn_repos is none) or (svn_repos|trim == '')) or svn_repo_backup.file_list != []

- name: remove svn-restore container
  docker_container:
    name: 'svn_restre'
    state: absent
# *****************************************************************************
# cleanup

- name: Remove files
  file:
    path: '{{ host_svn_docker_restore_dir }}'
    state: absent

- name: State file
  shell: 'date --rfc-3339=seconds > {{ docker_restore_config_base_dir }}/{{ svn_dv_name }}/restore.date.txt'
  when: st_svn_restore.stat.exists == False
