---
- name: Check for local directory to store NCD SVN Export
  run_once: true
  sudo: false
  local_action:
    module: file
    mode: 0775
    path: "{{ working_directory }}ncd_release/"
    state: directory

- name: Gathering needed NCD files locally
  run_once: true
  sudo: false
  local_action:
    module: ncdrelease
    svn_username: "{{ username }}"
    svn_password: "{{ password }}"
    ncd_release_repo: "{{ repo }}"
    local_checkout_dir: "{{ working_directory }}ncd_release/"
    releases_status_logfile: "{{ working_directory }}/ncd_repo_status"

- name: Sychronizing NCD releases to server
  synchronize:
    src: "{{ local_working_directory | expanduser }}ncd_release/"
    dest: "/opt/ncd_release/"
    owner: no
