---

- name: Create Docker Configuration Directory
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'

- name: Configure Docker Daemon
  template: 
    dest: /etc/docker/daemon.json
    src: daemon.json.j2
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'
  register: docker_json

- name: Restart Docker Daemon
  service:
    name: docker
    enabled: yes
    state: reloaded
  when: docker_json.changed
