---
# file: roles/docker-common/tasks/ip_addr.yaml

- name: install needed network manager libs
  yum:
    name: NetworkManager-glib
    state: installed
  register: nm_packages

- name: Restart NetworkManager
  service:
    name: NetworkManager
    state: restarted
  when: nm_packages.changed

# nmcli always returns 'changed', so we need
# to manually detect changes to the interface file
- name: Get interface checksum
  command: nmcli connection show "{{ network_connection }}"
  register: network_pre

- name: Add service IP addresses
  command: nmcli connection modify '{{ network_connection }}' +ipv4.addresses '{{ item.value.ip_addr }}/16'
  with_dict: "{{ container_addr_map }}"
    
- sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  when: ansible_os_family == "RedHat"

- name: Get interface checksum
  command: nmcli connection show "{{ network_connection }}"
  register: network_post

- name: make IPs active if needed
  command: nmcli connection up "{{ network_connection }}"
  when: 
    - ( network_pre != network_post )
