- name: Create temp directory for policy creation
  command: mktemp -d /tmp/ansible-bacula-director.XXXXXXXX
  register: docker_tmp_dir

- name: Copy docker_bacula type enforcement file
  copy:
    src: docker_bacula.te
    dest: '{{ docker_tmp_dir.stdout }}/docker_bacula.te'
    owner: root
    group: root
    mode: 'u=rw,g=r,o='

- name: Run checkmodule on docker_bacula.te
  command: /usr/bin/checkmodule -M -m -o docker_bacula.mod docker_bacula.te
  args:
    chdir: '{{ docker_tmp_dir.stdout }}'
  when: ansible_os_family == "RedHat"

- name: Build docker_bacula module
  command: /usr/bin/semodule_package -o docker_bacula.pp -m docker_bacula.mod
  args:
    chdir: '{{ docker_tmp_dir.stdout }}'
  when: ansible_os_family == "RedHat"

- name: Install docker_bacula module
  command: /usr/sbin/semodule -i docker_bacula.pp
  args:
    chdir: '{{ docker_tmp_dir.stdout }}'
  when: ansible_os_family == "RedHat"

- name: Delete temp directory
  file:
    path: '{{ docker_tmp_dir.stdout }}'
    state: absent
