---
bacula_storage_config_dir: "/etc/bacula"
bacula_storage_name: "bacula-sd"
bacula_storage_port: 9103
bacula_storage_working_dir: "/var/spool/bacula"
bacula_storage_pid_dir: "/var/run"
bacula_storage_concurrent_jobs: 20
bacula_director_name: "bacula-dir"
bacula_director_password: ""
bacula_monitor_name: "bacula-mon"
bacula_monitor_password: ""
bacula_storage_device_name: "QuantumTape"
bacula_storage_device_type: Tape
bacula_storage_device_archive_device: "/dev/nst0"
bacula_storage_device_media_type: "tape"

# must pass in the following variables
# bacula_director_password: ''
# bacula_monitor_password: ''
