---
- name: get pool info
  command: /usr/bin/virsh pool-info virtstorage
  register: poolinfo
  ignore_errors: True
- name: define pool
  command: /usr/bin/virsh pool-define-as --name virtstorage --type logical --target /dev/virtstorage
  when: poolinfo.stdout.find('State') == -1
- name: start pool
  command: /usr/bin/virsh pool-start virtstorage
  when: poolinfo.stdout.find('State') == -1
- name: autostart pool
  command: /usr/bin/virsh pool-autostart virtstorage
