---
galaxy_info:
  author: ansible-ThoTeam
  description: Nexus Repository Manager 3.x (Sonatype)
  company: ThoTeam

  license: license (GPLv3)

  min_ansible_version: 2.2

  github_branch: master

  platforms:
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - xenial
        - artful
    - name: Debian
      versions:
        - jessie
        - stretch

  galaxy_tags:
    - nexus
    - nexus3
    - java
    - maven
    - npm
    - nuget
    - yum
    - docker
    - pypi
    - web

dependencies: []
