- name: Create temp directory for policy creation
  command: mktemp -d /tmp/ansible-bacula-director.XXXXXXXX
  register: bacula_director_tmp_dir
- name: Copy baculavirt type enforcement file
  copy: src=baculavirt.te
          dest={{ bacula_director_tmp_dir.stdout }}/baculavirt.te
          owner=root group=root mode=0640
- name: Run checkmodule on baculavirt.te
  command: /usr/bin/checkmodule -M -m -o baculavirt.mod baculavirt.te
  args:
    chdir: "{{ bacula_director_tmp_dir.stdout }}"
- name: Build baculavirt module
  command: /usr/bin/semodule_package -o baculavirt.pp -m baculavirt.mod
  args:
    chdir: "{{ bacula_director_tmp_dir.stdout }}"
- name: Install baculavirt module
  command: /usr/sbin/semodule -i baculavirt.pp
  args:
    chdir: "{{ bacula_director_tmp_dir.stdout }}"
- name: Delete temp directory
  file: path={{ bacula_director_tmp_dir.stdout }} state=absent
