---
# tasks file for sshd

- name: lockdown root user
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^[#]?PermitRootLogin .*$'
    line: 'PermitRootLogin no'
    state: present

- name: Set ssh ListenAddress
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^[#]ListenAddress .*$'
    line: 'ListenAddress {{ ansible_default_ipv4["address"] }}'
  when: 
    - ansible_os_family == "RedHat"
    - ansible_default_ipv4 is defined
    - ansible_default_ipv4.address is defined

- name: restart sshd service
  service:
    name: sshd
    state: restarted
